experiment:
  name: RNN_windows_LV
  tracking_uri: http://localhost:5000
  run_subdir: RNN_windows_025_run02

data:
  root: raw_data/lotka_volterra_trajectories_T50_beta05_20_IC
  train_val_subdir: train_val
  test_subdir: test
  val_ratio: 0.2
  seed: 42
  dataset:
    class: data_processing.datasets.TrajectoryWindowDataset
    params:
      input_length: 1000
      target_length: 100
      step: 10

model:
  class: models.Seq2SeqRNN.EncoderDecoderRNN
  params:
    state_dim: 2
    input_length: 1000
    target_length: 10
    hidden_dim: 64
    num_layers: 3
    lr: 1e-5

training:
  batch_size: 1024
  max_epochs: 10
  num_workers: 8
  shuffle: true