experiment:
  name: AP_MLP_alexis_002
  description: no teacher forcing, no autoregressive training, resume mode
  tracking_uri: http://localhost:5000
  run_subdir: mlp/a_6

data:
  root: data_processing/data/lotka_volterra_trajectories
  train_val_subdir: train_val
  test_subdir: test
  input_length: 100    # 100 timesteps of context at 100Hz = 1s
  target_length: 10   # 10 timesteps forecast at 100Hz = 0.1s
  step: 10             # Stride for sliding windows (5 = moderate overlap)
  decimation: 10      # Downsample from 1000Hz to 100Hz
  val_ratio: 0.3
  seed: 808
  dataset:
    class: data_processing.datasets.TrajectoryWindowDataset
    params:
      input_length: 100
      target_length: 10
      step: 10

model:
  class: models.MLP.WindowMLP
  params:
    state_dim: 2
    input_len: 100
    target_len: 10
    hidden_sizes: [256, 512, 256]
    lr: 1e-5
    activation: tanh  # Better for smooth oscillatory signals
    num_autoregressive_steps: 1    # 1: disabled auto regression training. 5 :5 steps Ã— 5 timesteps = 25 total autoregressive
    teacher_forcing_ratio: 1.0     # 100% ground truth, 0% predictions during training

training:
  batch_size: 256
  max_epochs: 16
  num_workers: 2
  shuffle: true