experiment:
  name: LVOdePINN
  tracking_uri: http://localhost:5000
  run_subdir: pinn_run2

data:
  root: raw_data/lotka_volterra_trajectories_T50
  train_val_subdir: train_val
  test_subdir: test
  decimation: 10
  val_ratio: 0.2
  seed: 42
  dataset:
    class: data_processing.datasets.OdePINNDataset
    params:
      device: cpu

model:
  class: models.PINN.LVOdePINN
  params:
    input_size: 1
    theta_dim: 4
    hidden_size: 128
    output_size: 2    
    n_layer: 5
    lr: 1e-5
    seed: 42
    t_max: 50
    loss_weights:
      residual: 500.0
      ic: 50.0
      data: 0.1

training:
  batch_size: 128
  num_workers: 4
  max_epochs: 2