experiment:
  name: MLP_windows_basic
  tracking_uri: http://localhost:5000

data:
  root: raw_data/chen_trajectories
  train_val_subdir: train_val
  test_subdir: test
  input_length: 2000   # q=10, seq_len=500 points --> seq = 5 seconds for T=500 seconds, T=50000 points
  target_length: 250
  step: 1
  decimation: 10
  val_ratio: 0.2
  seed: 42

model:
  state_dim: 4
  hidden_sizes: [128, 128, 128, 128]
  lr: 1e-5

training:
  batch_size: 64
  max_epochs: 15
  num_workers: 8
  shuffle: true