experiment:
  name: LVOdePINN
  tracking_uri: file:./mlruns
  run_subdir: pinn_run

data:
  root: data
  train_val_subdir: train_val
  test_subdir: test
  input_length: 64
  target_length: 16
  step: 1
  decimation: 2
  val_ratio: 0.2
  seed: 42
  dataset:
    class: data_processing.datasets.OdePINNDataset
    params:
      device: cuda

model:
  class: models.PINN.LVOdePINN
  params:
    lr: 1.0e-3
    n: 1
    state_dim: 2
    hidden_layers: [128, 128, 128]
    weight_data: 1.0
    weight_pde: 1.0

training:
  batch_size: 128
  num_workers: 4
  max_epochs: 300