experiment:
  name: LVPICOdePINN
  tracking_uri: http://localhost:5000
  run_subdir: pinn_run6

data:
  root: raw_data/lotka_volterra_trajectories_T50
  train_val_subdir: train_val
  test_subdir: test
  decimation: 10
  val_ratio: 0.2
  seed: 42
  dataset:
    class: data_processing.datasets.OdePINNDataset
    params:
      device: cpu

model:
  class: models.PINN.LVOdePICPINN
  params:
    input_size: 1
    theta_dim: 4
    hidden_size: 512
    output_size: 2    
    n_layer: 4
    lr: 0.5e-6
    seed: 42
    t_max: 50
    loss_weights:
      residual: 1.0
      ic: 1.0
      data: 1.0

training:
  batch_size: 1024
  num_workers: 4
  max_epochs: 2